let d = POST {"greeting": "Hello!"} to "https://http-dsl-test-api.herokuapp.com/set-greeting";
print(d);
let s = GET from "https://http-dsl-test-api.herokuapp.com/greeting";
print(s);
let userCookie = "user=Chris";
let cookie = GET from "https://http-dsl-test-api.herokuapp.com/user" with {"Cookie": userCookie};
print(cookie)
