print(
  {"name": "Chris", "Education": 
    {"college": "Cornell", "degree": "Computer Science"}
  }
);
let x = 0;
let age = 20;
let json = {"num": "$x", "extra": {"name": "Ansh", "age": "$age"}};
print(json)